import base64
import hashlib
import secrets
from app.models.vpn_profile import VPNProfile


def demo_private_key() -> str:
    """Generates a demo-safe mock private key."""
    return base64.b64encode(secrets.token_bytes(32)).decode("ascii")


def demo_public_key(private_key: str) -> str:
    """Derives a mock public key from a private key."""
    digest = hashlib.sha256(private_key.encode("utf-8")).digest()
    return base64.b64encode(digest).decode("ascii")


def demo_preshared_key() -> str:
    """Generates a demo-safe mock preshared key."""
    return base64.b64encode(secrets.token_bytes(32)).decode("ascii")


def render_config(profile: VPNProfile, server_public_key: str) -> str:
    """Renders the standard WireGuard client configuration file."""
    return "\n".join(
        [
            "# Demo-safe WireGuard configuration generated by VPN Management System",
            "# Replace demo keys with real wg-generated keys before production use.",
            "",
            "[Interface]",
            f"PrivateKey = {profile.key.private_key}",
            f"Address = {profile.assigned_ip}",
            f"DNS = {profile.dns}",
            "",
            "[Peer]",
            f"PublicKey = {server_public_key}",
            f"PresharedKey = {profile.key.preshared_key}",
            f"Endpoint = {profile.endpoint}",
            f"AllowedIPs = {profile.allowed_ips}",
            "PersistentKeepalive = 25",
            "",
        ]
    )
